'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Sparkles, Wand2 } from 'lucide-react'
import AiTripChat from '@/features/ai-planner/components/AiTripChat'
import GeneratedTripPreview from '@/features/ai-planner/components/GeneratedTripPreview'
import { GeneratedTrip } from '@/features/ai-planner/services/aiTripService'
import { useItineraries } from '@/features/planner/hooks/useItineraries'
import { dayService } from '@/features/planner/services/dayService'
import { activityService } from '@/features/planner/services/activityService'
import { useToast } from '@/contexts/ToastContext'
import { useLocalizedTrip } from '@/hooks/useLocalizedTrip'

export default function AiPlannerPage() {
  const router = useRouter()
  const t = useLocalizedTrip()
  const { success, error: showError } = useToast()
  const { createItinerary } = useItineraries()

  const [generatedTrip, setGeneratedTrip] = useState<GeneratedTrip | null>(null)
  const [isCreating, setIsCreating] = useState(false)

  const handleTripGenerated = (trip: GeneratedTrip) => {
    setGeneratedTrip(trip)
  }

  const handleCreateTrip = async () => {
    if (!generatedTrip) return

    setIsCreating(true)

    try {
      // Calculate dates
      const startDate = new Date()
      const endDate = new Date()
      endDate.setDate(startDate.getDate() + generatedTrip.duration - 1)

      // Create the itinerary
      const itinerary = await createItinerary({
        title: generatedTrip.title,
        description: generatedTrip.description,
        start_date: startDate.toISOString().split('T')[0],
        end_date: endDate.toISOString().split('T')[0],
        destinations: [generatedTrip.destination],
        total_budget: generatedTrip.estimatedBudget,
      })

      if (!itinerary) {
        throw new Error('Failed to create itinerary')
      }

      // Get created days (auto-generated by createItinerary)
      const days = await dayService.getByItinerary(itinerary.id)

      // Create activities for each day
      for (const generatedDay of generatedTrip.days) {
        const existingDay = days.find(d => d.day_number === generatedDay.dayNumber)

        if (existingDay) {
          // Update day title
          await dayService.update(existingDay.id, { title: generatedDay.title })

          // Create activities for this day
          for (let i = 0; i < generatedDay.activities.length; i++) {
            const activity = generatedDay.activities[i]
            await activityService.create({
              day_id: existingDay.id,
              title: activity.name,
              description: activity.description,
              start_time: convertTo24Hour(activity.time),
              estimated_cost: activity.cost,
              location: generatedTrip.destination,
              place_type: activity.category,
              order_index: i,
            })
          }
        }
      }

      success(`${t.trip} created successfully!`)
      router.push(`/planner/${itinerary.id}`)
    } catch (error) {
      console.error('Error creating trip:', error)
    } finally {
      setIsCreating(false)
    }
  }

  const handleStartOver = () => {
    setGeneratedTrip(null)
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-black">
      {/* Header */}
      <div className="sticky top-0 z-40 bg-white dark:bg-gray-900 border-b border-gray-200 dark:border-gray-800">
        <div className="max-w-4xl mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <button
                onClick={() => router.back()}
                className="p-2 text-gray-500 hover:text-gray-700 dark:hover:text-gray-300 -ml-2"
              >
                <ArrowLeft className="w-5 h-5" />
              </button>
              <div className="flex items-center gap-2">
                <div className="w-10 h-10 bg-gradient-to-br from-teal-400 to-blue-500 rounded-xl flex items-center justify-center">
                  <Wand2 className="w-5 h-5 text-white" />
                </div>
                <div>
                  <h1 className="text-xl font-bold text-gray-900 dark:text-white">
                    AI {t.trip} Planner
                  </h1>
                  <p className="text-xs text-gray-500 dark:text-gray-400">
                    Describe your dream trip
                  </p>
                </div>
              </div>
            </div>

            {generatedTrip && (
              <button
                onClick={handleStartOver}
                className="text-sm text-teal-600 dark:text-teal-400 hover:underline"
              >
                Start Over
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-6">
        {!generatedTrip ? (
          // Chat Interface
          <div className="h-[calc(100vh-180px)] min-h-[500px]">
            <AiTripChat onTripGenerated={handleTripGenerated} />
          </div>
        ) : (
          // Generated Trip Preview
          <div className="space-y-4">
            <div className="flex items-center gap-2 text-teal-600 dark:text-teal-400">
              <Sparkles className="w-5 h-5" />
              <span className="font-medium">Your AI-generated itinerary is ready!</span>
            </div>

            <GeneratedTripPreview
              trip={generatedTrip}
              onCreateTrip={handleCreateTrip}
              onCustomize={handleStartOver}
            />

            {isCreating && (
              <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
                <div className="bg-white dark:bg-gray-800 rounded-xl p-6 text-center">
                  <div className="w-12 h-12 border-4 border-teal-500 border-t-transparent rounded-full animate-spin mx-auto mb-4" />
                  <p className="text-gray-900 dark:text-white font-medium">
                    Creating your {t.trip}...
                  </p>
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Features Banner */}
      {!generatedTrip && (
        <div className="fixed bottom-0 left-0 right-0 bg-gradient-to-t from-gray-50 dark:from-black pt-8 pb-4 pointer-events-none">
          <div className="max-w-4xl mx-auto px-4">
            <div className="flex justify-center gap-6 text-xs text-gray-500 dark:text-gray-400">
              <span className="flex items-center gap-1">
                <span className="w-2 h-2 bg-teal-500 rounded-full" />
                Natural language input
              </span>
              <span className="flex items-center gap-1">
                <span className="w-2 h-2 bg-blue-500 rounded-full" />
                Budget optimization
              </span>
              <span className="flex items-center gap-1">
                <span className="w-2 h-2 bg-purple-500 rounded-full" />
                Instant itinerary
              </span>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// Helper function to convert 12-hour time to 24-hour format
function convertTo24Hour(time12: string): string {
  const [time, modifier] = time12.split(' ')
  let [hours, minutes] = time.split(':')

  if (hours === '12') {
    hours = modifier === 'AM' ? '00' : '12'
  } else if (modifier === 'PM') {
    hours = String(parseInt(hours, 10) + 12)
  }

  return `${hours.padStart(2, '0')}:${minutes || '00'}`
}
