import { createClient } from '@supabase/supabase-js'
import { config } from 'dotenv'

// Load environment variables from .env.local
config({ path: '.env.local' })

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

const supabase = createClient(supabaseUrl, supabaseServiceKey)

const places = [
  // BORACAY
  {
    name: 'White Beach',
    description: 'Famous 4km stretch of white sand beach, perfect for swimming and sunset watching',
    location: 'Boracay',
    address: 'White Beach, Malay, Aklan',
    coordinates: { x: 11.9674, y: 121.9248 },
    place_type: 'beach',
    category: 'beach',
    price_range: 'budget',
    estimated_cost: 0,
    tags: ['beach', 'swimming', 'sunset', 'boracay', 'white-sand'],
    is_featured: true,
    average_rating: 4.8,
    total_reviews: 1250,
  },
  {
    name: "D'Mall Boracay",
    description: 'Main shopping and dining hub with restaurants, bars, and souvenir shops',
    location: 'Boracay',
    address: 'Station 2, Boracay',
    coordinates: { x: 11.9631, y: 121.9244 },
    place_type: 'shopping',
    category: 'mall',
    price_range: 'moderate',
    estimated_cost: 500,
    tags: ['shopping', 'food', 'nightlife', 'boracay'],
    is_featured: true,
    average_rating: 4.5,
    total_reviews: 890,
  },
  {
    name: "Ariel's Point",
    description: 'Cliff diving, snorkeling, and party spot with unlimited drinks',
    location: 'Boracay',
    address: 'Buruanga, Aklan',
    coordinates: { x: 11.8833, y: 121.9167 },
    place_type: 'activity',
    category: 'cliff-diving',
    price_range: 'moderate',
    estimated_cost: 2500,
    tags: ['cliff-diving', 'snorkeling', 'party', 'boracay', 'adventure'],
    is_featured: true,
    average_rating: 4.7,
    total_reviews: 654,
  },
  {
    name: 'Puka Shell Beach',
    description: 'Quieter beach known for puka shells, less crowded than White Beach',
    location: 'Boracay',
    address: 'Yapak, Boracay',
    coordinates: { x: 11.9892, y: 121.9297 },
    place_type: 'beach',
    category: 'beach',
    price_range: 'budget',
    estimated_cost: 0,
    tags: ['beach', 'quiet', 'shells', 'boracay'],
    is_featured: false,
    average_rating: 4.4,
    total_reviews: 432,
  },
  {
    name: 'Island Hopping Boracay',
    description: 'Visit Crystal Cove, Crocodile Island, and snorkeling spots',
    location: 'Boracay',
    address: 'Boracay Island',
    coordinates: { x: 11.9674, y: 121.9248 },
    place_type: 'activity',
    category: 'island-hopping',
    price_range: 'moderate',
    estimated_cost: 1500,
    tags: ['island-hopping', 'snorkeling', 'boat-tour', 'boracay'],
    is_featured: true,
    average_rating: 4.6,
    total_reviews: 567,
  },

  // PALAWAN - EL NIDO
  {
    name: 'Big Lagoon',
    description: 'Stunning lagoon with towering limestone cliffs, part of Tour A',
    location: 'El Nido',
    address: 'Miniloc Island, El Nido',
    coordinates: { x: 11.1833, y: 119.3667 },
    place_type: 'attraction',
    category: 'lagoon',
    price_range: 'moderate',
    estimated_cost: 1400,
    tags: ['lagoon', 'kayaking', 'el-nido', 'tour-a', 'limestone'],
    is_featured: true,
    average_rating: 4.9,
    total_reviews: 2341,
  },
  {
    name: 'Small Lagoon',
    description: 'Crystal clear lagoon accessible by kayak through a small opening',
    location: 'El Nido',
    address: 'Miniloc Island, El Nido',
    coordinates: { x: 11.175, y: 119.3583 },
    place_type: 'attraction',
    category: 'lagoon',
    price_range: 'moderate',
    estimated_cost: 1400,
    tags: ['lagoon', 'kayaking', 'el-nido', 'tour-a'],
    is_featured: true,
    average_rating: 4.8,
    total_reviews: 1876,
  },
  {
    name: 'Nacpan Beach',
    description: 'Long stretch of golden sand beach, one of the best in the Philippines',
    location: 'El Nido',
    address: 'Nacpan, El Nido',
    coordinates: { x: 11.3167, y: 119.4333 },
    place_type: 'beach',
    category: 'beach',
    price_range: 'budget',
    estimated_cost: 0,
    tags: ['beach', 'golden-sand', 'el-nido', 'swimming'],
    is_featured: true,
    average_rating: 4.7,
    total_reviews: 1543,
  },
  {
    name: 'Secret Lagoon',
    description: 'Hidden lagoon inside a rock formation, magical swimming spot',
    location: 'El Nido',
    address: 'Miniloc Island, El Nido',
    coordinates: { x: 11.1833, y: 119.3583 },
    place_type: 'attraction',
    category: 'lagoon',
    price_range: 'moderate',
    estimated_cost: 1400,
    tags: ['lagoon', 'secret', 'el-nido', 'tour-a', 'swimming'],
    is_featured: false,
    average_rating: 4.6,
    total_reviews: 987,
  },
  {
    name: 'El Nido Tour A',
    description: 'Big Lagoon, Small Lagoon, Secret Lagoon, Shimizu Island',
    location: 'El Nido',
    address: 'El Nido, Palawan',
    coordinates: { x: 11.1833, y: 119.3917 },
    place_type: 'activity',
    category: 'island-hopping',
    price_range: 'moderate',
    estimated_cost: 1400,
    tags: ['island-hopping', 'el-nido', 'tour-a', 'lagoons'],
    is_featured: true,
    average_rating: 4.8,
    total_reviews: 3421,
  },
  {
    name: 'El Nido Tour C',
    description: 'Hidden Beach, Secret Beach, Matinloc Shrine, Helicopter Island',
    location: 'El Nido',
    address: 'El Nido, Palawan',
    coordinates: { x: 11.1833, y: 119.3917 },
    place_type: 'activity',
    category: 'island-hopping',
    price_range: 'moderate',
    estimated_cost: 1500,
    tags: ['island-hopping', 'el-nido', 'tour-c', 'beaches'],
    is_featured: true,
    average_rating: 4.7,
    total_reviews: 2876,
  },

  // PALAWAN - CORON
  {
    name: 'Kayangan Lake',
    description: "Crystal clear lake often called the cleanest lake in the Philippines",
    location: 'Coron',
    address: 'Coron Island, Palawan',
    coordinates: { x: 11.9833, y: 120.2333 },
    place_type: 'attraction',
    category: 'lake',
    price_range: 'moderate',
    estimated_cost: 1500,
    tags: ['lake', 'swimming', 'coron', 'cleanest-lake', 'viewpoint'],
    is_featured: true,
    average_rating: 4.9,
    total_reviews: 4532,
  },
  {
    name: 'Twin Lagoon',
    description: 'Two lagoons connected by a small gap in the rock, hot and cold water',
    location: 'Coron',
    address: 'Coron Island, Palawan',
    coordinates: { x: 11.975, y: 120.2167 },
    place_type: 'attraction',
    category: 'lagoon',
    price_range: 'moderate',
    estimated_cost: 1500,
    tags: ['lagoon', 'swimming', 'coron', 'hot-spring'],
    is_featured: true,
    average_rating: 4.7,
    total_reviews: 2341,
  },
  {
    name: 'Barracuda Lake',
    description: 'Unique diving spot with hot and cold thermoclines',
    location: 'Coron',
    address: 'Coron Island, Palawan',
    coordinates: { x: 11.9833, y: 120.225 },
    place_type: 'activity',
    category: 'diving',
    price_range: 'moderate',
    estimated_cost: 1500,
    tags: ['diving', 'lake', 'coron', 'thermocline'],
    is_featured: false,
    average_rating: 4.6,
    total_reviews: 876,
  },
  {
    name: 'Japanese Shipwreck',
    description: 'WWII shipwreck diving site, one of the best in Asia',
    location: 'Coron',
    address: 'Coron Bay, Palawan',
    coordinates: { x: 11.9917, y: 120.2083 },
    place_type: 'activity',
    category: 'diving',
    price_range: 'moderate',
    estimated_cost: 2500,
    tags: ['diving', 'wreck', 'coron', 'wwii', 'scuba'],
    is_featured: true,
    average_rating: 4.8,
    total_reviews: 1234,
  },
  {
    name: 'Mt. Tapyas',
    description: 'Climb 724 steps for panoramic sunset views of Coron town',
    location: 'Coron',
    address: 'Coron Town, Palawan',
    coordinates: { x: 11.9917, y: 120.2083 },
    place_type: 'attraction',
    category: 'viewpoint',
    price_range: 'budget',
    estimated_cost: 0,
    tags: ['hiking', 'viewpoint', 'sunset', 'coron', 'free'],
    is_featured: true,
    average_rating: 4.5,
    total_reviews: 2145,
  },

  // CEBU
  {
    name: 'Kawasan Falls',
    description: 'Three-tiered waterfall famous for canyoneering adventures',
    location: 'Cebu',
    address: 'Badian, Cebu',
    coordinates: { x: 9.8167, y: 123.3833 },
    place_type: 'attraction',
    category: 'waterfall',
    price_range: 'moderate',
    estimated_cost: 1000,
    tags: ['waterfall', 'canyoneering', 'cebu', 'swimming', 'adventure'],
    is_featured: true,
    average_rating: 4.8,
    total_reviews: 3456,
  },
  {
    name: 'Oslob Whale Sharks',
    description: 'Swim with gentle whale sharks (controversial but popular)',
    location: 'Cebu',
    address: 'Oslob, Cebu',
    coordinates: { x: 9.4667, y: 123.3833 },
    place_type: 'activity',
    category: 'wildlife',
    price_range: 'moderate',
    estimated_cost: 1500,
    tags: ['whale-sharks', 'swimming', 'cebu', 'wildlife'],
    is_featured: true,
    average_rating: 4.5,
    total_reviews: 5678,
  },
  {
    name: 'Moalboal Sardine Run',
    description: 'Snorkel with millions of sardines in a massive bait ball',
    location: 'Cebu',
    address: 'Moalboal, Cebu',
    coordinates: { x: 9.95, y: 123.4 },
    place_type: 'activity',
    category: 'snorkeling',
    price_range: 'budget',
    estimated_cost: 500,
    tags: ['snorkeling', 'sardines', 'cebu', 'diving', 'moalboal'],
    is_featured: true,
    average_rating: 4.7,
    total_reviews: 2345,
  },
  {
    name: 'Temple of Leah',
    description: 'Roman-inspired temple with panoramic views of Cebu City',
    location: 'Cebu',
    address: 'Cebu City',
    coordinates: { x: 10.35, y: 123.8667 },
    place_type: 'attraction',
    category: 'temple',
    price_range: 'budget',
    estimated_cost: 100,
    tags: ['temple', 'viewpoint', 'cebu-city', 'architecture'],
    is_featured: false,
    average_rating: 4.3,
    total_reviews: 1234,
  },
  {
    name: "Magellan's Cross",
    description: 'Historic cross planted by Ferdinand Magellan in 1521',
    location: 'Cebu',
    address: 'Cebu City',
    coordinates: { x: 10.2933, y: 123.9022 },
    place_type: 'attraction',
    category: 'historical',
    price_range: 'budget',
    estimated_cost: 0,
    tags: ['historical', 'cebu-city', 'landmark', 'free'],
    is_featured: true,
    average_rating: 4.4,
    total_reviews: 3456,
  },

  // SIARGAO
  {
    name: 'Cloud 9',
    description: 'World-famous surfing spot with powerful reef breaks',
    location: 'Siargao',
    address: 'General Luna, Siargao',
    coordinates: { x: 9.85, y: 126.1167 },
    place_type: 'beach',
    category: 'surfing',
    price_range: 'budget',
    estimated_cost: 50,
    tags: ['surfing', 'siargao', 'cloud-9', 'waves', 'pro-surfers'],
    is_featured: true,
    average_rating: 4.9,
    total_reviews: 4567,
  },
  {
    name: 'Sugba Lagoon',
    description: 'Stunning turquoise lagoon perfect for paddleboarding and swimming',
    location: 'Siargao',
    address: 'Del Carmen, Siargao',
    coordinates: { x: 9.8833, y: 125.9833 },
    place_type: 'attraction',
    category: 'lagoon',
    price_range: 'moderate',
    estimated_cost: 1000,
    tags: ['lagoon', 'paddleboard', 'siargao', 'swimming'],
    is_featured: true,
    average_rating: 4.8,
    total_reviews: 2345,
  },
  {
    name: 'Magpupungko Rock Pools',
    description: 'Natural tidal pools with crystal clear water',
    location: 'Siargao',
    address: 'Pilar, Siargao',
    coordinates: { x: 9.9333, y: 126.0833 },
    place_type: 'attraction',
    category: 'rock-pools',
    price_range: 'budget',
    estimated_cost: 50,
    tags: ['rock-pools', 'swimming', 'siargao', 'low-tide'],
    is_featured: true,
    average_rating: 4.7,
    total_reviews: 1987,
  },
  {
    name: 'Naked Island',
    description: 'Small sandbar island with no shade, pure white sand',
    location: 'Siargao',
    address: 'General Luna, Siargao',
    coordinates: { x: 9.8167, y: 126.15 },
    place_type: 'beach',
    category: 'island',
    price_range: 'moderate',
    estimated_cost: 1500,
    tags: ['island', 'sandbar', 'siargao', 'island-hopping'],
    is_featured: false,
    average_rating: 4.5,
    total_reviews: 876,
  },
  {
    name: 'Sohoton Cove',
    description: 'Enchanting lagoon with stingless jellyfish and caves',
    location: 'Siargao',
    address: 'Del Carmen, Siargao',
    coordinates: { x: 9.9, y: 125.9667 },
    place_type: 'attraction',
    category: 'lagoon',
    price_range: 'moderate',
    estimated_cost: 1500,
    tags: ['lagoon', 'jellyfish', 'caves', 'siargao', 'sohoton'],
    is_featured: true,
    average_rating: 4.8,
    total_reviews: 1654,
  },

  // BOHOL
  {
    name: 'Chocolate Hills',
    description: 'Over 1,200 cone-shaped hills that turn brown in dry season',
    location: 'Bohol',
    address: 'Carmen, Bohol',
    coordinates: { x: 9.8, y: 124.1333 },
    place_type: 'attraction',
    category: 'geological',
    price_range: 'budget',
    estimated_cost: 50,
    tags: ['chocolate-hills', 'bohol', 'viewpoint', 'landmark'],
    is_featured: true,
    average_rating: 4.6,
    total_reviews: 5678,
  },
  {
    name: 'Tarsier Sanctuary',
    description: "See the world's smallest primates in their natural habitat",
    location: 'Bohol',
    address: 'Loboc, Bohol',
    coordinates: { x: 9.6333, y: 124.0167 },
    place_type: 'attraction',
    category: 'wildlife',
    price_range: 'budget',
    estimated_cost: 100,
    tags: ['tarsier', 'wildlife', 'bohol', 'sanctuary'],
    is_featured: true,
    average_rating: 4.5,
    total_reviews: 3456,
  },
  {
    name: 'Loboc River Cruise',
    description: 'Floating restaurant cruise along the scenic Loboc River',
    location: 'Bohol',
    address: 'Loboc, Bohol',
    coordinates: { x: 9.6333, y: 124.0167 },
    place_type: 'activity',
    category: 'cruise',
    price_range: 'moderate',
    estimated_cost: 600,
    tags: ['river-cruise', 'lunch', 'bohol', 'loboc'],
    is_featured: true,
    average_rating: 4.4,
    total_reviews: 2345,
  },
  {
    name: 'Panglao Beach',
    description: 'White sand beach with great diving and snorkeling',
    location: 'Bohol',
    address: 'Panglao Island, Bohol',
    coordinates: { x: 9.5667, y: 123.7667 },
    place_type: 'beach',
    category: 'beach',
    price_range: 'budget',
    estimated_cost: 0,
    tags: ['beach', 'diving', 'panglao', 'bohol', 'white-sand'],
    is_featured: true,
    average_rating: 4.6,
    total_reviews: 4567,
  },
  {
    name: 'Balicasag Island',
    description: 'Marine sanctuary with excellent diving and dolphin watching',
    location: 'Bohol',
    address: 'Panglao, Bohol',
    coordinates: { x: 9.5167, y: 123.6833 },
    place_type: 'activity',
    category: 'diving',
    price_range: 'moderate',
    estimated_cost: 2000,
    tags: ['diving', 'dolphins', 'marine-sanctuary', 'bohol', 'island-hopping'],
    is_featured: true,
    average_rating: 4.7,
    total_reviews: 1876,
  },

  // MANILA
  {
    name: 'Intramuros',
    description: 'Historic walled city from Spanish colonial era',
    location: 'Manila',
    address: 'Intramuros, Manila',
    coordinates: { x: 14.5889, y: 120.975 },
    place_type: 'attraction',
    category: 'historical',
    price_range: 'budget',
    estimated_cost: 100,
    tags: ['historical', 'manila', 'spanish', 'walled-city', 'walking-tour'],
    is_featured: true,
    average_rating: 4.5,
    total_reviews: 6789,
  },
  {
    name: 'Rizal Park',
    description: 'Large urban park with monuments, gardens, and the National Museum',
    location: 'Manila',
    address: 'Ermita, Manila',
    coordinates: { x: 14.5833, y: 120.9833 },
    place_type: 'attraction',
    category: 'park',
    price_range: 'budget',
    estimated_cost: 0,
    tags: ['park', 'manila', 'rizal', 'national-museum', 'free'],
    is_featured: true,
    average_rating: 4.4,
    total_reviews: 5432,
  },
  {
    name: 'BGC (Bonifacio Global City)',
    description: 'Modern district with restaurants, shops, and nightlife',
    location: 'Manila',
    address: 'Taguig, Metro Manila',
    coordinates: { x: 14.55, y: 121.05 },
    place_type: 'shopping',
    category: 'district',
    price_range: 'moderate',
    estimated_cost: 1000,
    tags: ['shopping', 'dining', 'nightlife', 'manila', 'modern'],
    is_featured: false,
    average_rating: 4.3,
    total_reviews: 3456,
  },
  {
    name: 'Binondo Chinatown',
    description: "World's oldest Chinatown with amazing street food",
    location: 'Manila',
    address: 'Binondo, Manila',
    coordinates: { x: 14.5997, y: 120.9736 },
    place_type: 'attraction',
    category: 'food-district',
    price_range: 'budget',
    estimated_cost: 500,
    tags: ['chinatown', 'food', 'manila', 'street-food', 'oldest'],
    is_featured: true,
    average_rating: 4.6,
    total_reviews: 4567,
  },
  {
    name: 'San Agustin Church',
    description: 'UNESCO World Heritage baroque church from 1607',
    location: 'Manila',
    address: 'Intramuros, Manila',
    coordinates: { x: 14.5878, y: 120.9753 },
    place_type: 'attraction',
    category: 'church',
    price_range: 'budget',
    estimated_cost: 0,
    tags: ['church', 'unesco', 'manila', 'baroque', 'historical'],
    is_featured: true,
    average_rating: 4.7,
    total_reviews: 3245,
  },

  // BAGUIO
  {
    name: 'Burnham Park',
    description: 'Iconic park with boat rides, gardens, and the famous orchidarium',
    location: 'Baguio',
    address: 'Baguio City',
    coordinates: { x: 16.4119, y: 120.5967 },
    place_type: 'attraction',
    category: 'park',
    price_range: 'budget',
    estimated_cost: 100,
    tags: ['park', 'baguio', 'boat-rides', 'gardens'],
    is_featured: true,
    average_rating: 4.4,
    total_reviews: 4567,
  },
  {
    name: 'Mines View Park',
    description: 'Viewpoint overlooking abandoned mining town and mountains',
    location: 'Baguio',
    address: 'Baguio City',
    coordinates: { x: 16.4167, y: 120.6167 },
    place_type: 'attraction',
    category: 'viewpoint',
    price_range: 'budget',
    estimated_cost: 0,
    tags: ['viewpoint', 'baguio', 'mountains', 'souvenir-shopping'],
    is_featured: true,
    average_rating: 4.3,
    total_reviews: 3456,
  },
  {
    name: 'Strawberry Farm',
    description: 'Pick your own strawberries at La Trinidad farms',
    location: 'Baguio',
    address: 'La Trinidad, Benguet',
    coordinates: { x: 16.45, y: 120.5833 },
    place_type: 'activity',
    category: 'farm',
    price_range: 'budget',
    estimated_cost: 300,
    tags: ['strawberry', 'farm', 'baguio', 'pick-your-own'],
    is_featured: true,
    average_rating: 4.2,
    total_reviews: 2345,
  },
  {
    name: 'Session Road',
    description: 'Main commercial street with shops, cafes, and restaurants',
    location: 'Baguio',
    address: 'Baguio City',
    coordinates: { x: 16.4117, y: 120.5958 },
    place_type: 'shopping',
    category: 'street',
    price_range: 'moderate',
    estimated_cost: 500,
    tags: ['shopping', 'baguio', 'food', 'cafes'],
    is_featured: false,
    average_rating: 4.1,
    total_reviews: 1876,
  },

  // VIGAN
  {
    name: 'Calle Crisologo',
    description: 'UNESCO heritage cobblestone street with Spanish colonial houses',
    location: 'Vigan',
    address: 'Vigan City, Ilocos Sur',
    coordinates: { x: 17.5747, y: 120.3869 },
    place_type: 'attraction',
    category: 'heritage-street',
    price_range: 'budget',
    estimated_cost: 0,
    tags: ['heritage', 'vigan', 'unesco', 'spanish-colonial', 'cobblestone'],
    is_featured: true,
    average_rating: 4.7,
    total_reviews: 5678,
  },
  {
    name: 'Vigan Empanada',
    description: 'Famous orange empanada with egg, try at Plaza Burgos',
    location: 'Vigan',
    address: 'Plaza Burgos, Vigan',
    coordinates: { x: 17.575, y: 120.3867 },
    place_type: 'restaurant',
    category: 'local-food',
    price_range: 'budget',
    estimated_cost: 50,
    tags: ['empanada', 'food', 'vigan', 'local-delicacy'],
    is_featured: true,
    average_rating: 4.6,
    total_reviews: 3456,
  },
  {
    name: 'Kalesa Ride Vigan',
    description: 'Horse-drawn carriage tour around the heritage city',
    location: 'Vigan',
    address: 'Vigan City',
    coordinates: { x: 17.5747, y: 120.3869 },
    place_type: 'activity',
    category: 'tour',
    price_range: 'budget',
    estimated_cost: 150,
    tags: ['kalesa', 'tour', 'vigan', 'heritage'],
    is_featured: true,
    average_rating: 4.5,
    total_reviews: 2345,
  },

  // BATANES
  {
    name: 'Basco Lighthouse',
    description: 'Iconic lighthouse with stunning ocean views',
    location: 'Batanes',
    address: 'Basco, Batanes',
    coordinates: { x: 20.45, y: 121.9667 },
    place_type: 'attraction',
    category: 'lighthouse',
    price_range: 'budget',
    estimated_cost: 0,
    tags: ['lighthouse', 'batanes', 'viewpoint', 'ocean'],
    is_featured: true,
    average_rating: 4.8,
    total_reviews: 1234,
  },
  {
    name: 'Marlboro Country',
    description: 'Rolling green hills that look like scenes from Marlboro ads',
    location: 'Batanes',
    address: 'Mahatao, Batanes',
    coordinates: { x: 20.4, y: 121.95 },
    place_type: 'attraction',
    category: 'landscape',
    price_range: 'budget',
    estimated_cost: 0,
    tags: ['hills', 'batanes', 'scenery', 'instagram'],
    is_featured: true,
    average_rating: 4.9,
    total_reviews: 2345,
  },
  {
    name: 'Valugan Boulder Beach',
    description: 'Unique beach covered in large volcanic boulders',
    location: 'Batanes',
    address: 'Basco, Batanes',
    coordinates: { x: 20.4667, y: 121.9833 },
    place_type: 'beach',
    category: 'beach',
    price_range: 'budget',
    estimated_cost: 0,
    tags: ['beach', 'boulders', 'batanes', 'volcanic'],
    is_featured: true,
    average_rating: 4.7,
    total_reviews: 987,
  },
  {
    name: 'Honesty Coffee Shop',
    description: 'Unmanned store based on the honor system',
    location: 'Batanes',
    address: 'Ivana, Batanes',
    coordinates: { x: 20.3667, y: 121.9167 },
    place_type: 'attraction',
    category: 'unique',
    price_range: 'budget',
    estimated_cost: 100,
    tags: ['honesty', 'coffee', 'batanes', 'unique'],
    is_featured: true,
    average_rating: 4.6,
    total_reviews: 1543,
  },

  // RESTAURANTS - Sample food spots
  {
    name: 'Manam',
    description: 'Modern Filipino cuisine with a twist, famous for sizzling sinigang',
    location: 'Manila',
    address: 'Multiple locations, Manila',
    coordinates: { x: 14.5547, y: 121.0244 },
    place_type: 'restaurant',
    category: 'filipino',
    price_range: 'moderate',
    estimated_cost: 800,
    tags: ['restaurant', 'filipino', 'manila', 'sinigang'],
    is_featured: true,
    average_rating: 4.5,
    total_reviews: 6789,
  },
  {
    name: 'Jollibee',
    description: "Philippines' favorite fast food - try the Chickenjoy!",
    location: 'Manila',
    address: 'Nationwide',
    coordinates: { x: 14.5995, y: 120.9842 },
    place_type: 'restaurant',
    category: 'fast-food',
    price_range: 'budget',
    estimated_cost: 200,
    tags: ['fast-food', 'chickenjoy', 'filipino', 'manila'],
    is_featured: false,
    average_rating: 4.3,
    total_reviews: 12345,
  },
  {
    name: 'Cafe Ilang-Ilang',
    description: 'Elegant buffet at Manila Hotel, Filipino and international cuisine',
    location: 'Manila',
    address: 'Manila Hotel, Rizal Park',
    coordinates: { x: 14.5847, y: 120.9778 },
    place_type: 'restaurant',
    category: 'buffet',
    price_range: 'luxury',
    estimated_cost: 2500,
    tags: ['buffet', 'hotel', 'manila', 'fine-dining'],
    is_featured: false,
    average_rating: 4.4,
    total_reviews: 2345,
  },
]

async function seed() {
  console.log('Seeding places...')

  // Delete existing places first (optional - comment out if you want to keep existing)
  // const { error: deleteError } = await supabase.from('places').delete().neq('id', '00000000-0000-0000-0000-000000000000')
  // if (deleteError) console.error('Error deleting existing places:', deleteError)

  // Insert places
  for (const place of places) {
    // Convert coordinates to PostgreSQL POINT format string
    const coords = place.coordinates
      ? `(${place.coordinates.x}, ${place.coordinates.y})`
      : null

    const { error } = await supabase.from('places').upsert(
      {
        ...place,
        coordinates: coords,
        is_active: true,
      },
      { onConflict: 'name' }
    )

    if (error) {
      console.error(`Error inserting ${place.name}:`, error.message)
    } else {
      console.log(`✓ ${place.name}`)
    }
  }

  console.log(`\nSeeded ${places.length} places!`)
}

seed().catch(console.error)
