-- Add ALL missing columns to places table
ALTER TABLE places ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE places ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE places ADD COLUMN IF NOT EXISTS price_range TEXT;
ALTER TABLE places ADD COLUMN IF NOT EXISTS estimated_cost DECIMAL(10,2);
ALTER TABLE places ADD COLUMN IF NOT EXISTS opening_hours TEXT;
ALTER TABLE places ADD COLUMN IF NOT EXISTS contact_phone TEXT;
ALTER TABLE places ADD COLUMN IF NOT EXISTS contact_email TEXT;
ALTER TABLE places ADD COLUMN IF NOT EXISTS website TEXT;
ALTER TABLE places ADD COLUMN IF NOT EXISTS average_rating DECIMAL(2,1) DEFAULT 0;
ALTER TABLE places ADD COLUMN IF NOT EXISTS total_reviews INTEGER DEFAULT 0;
ALTER TABLE places ADD COLUMN IF NOT EXISTS is_featured BOOLEAN DEFAULT FALSE;
ALTER TABLE places ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE places ADD COLUMN IF NOT EXISTS tags TEXT[];
ALTER TABLE places ADD COLUMN IF NOT EXISTS photos TEXT[];

-- Add unique constraint on name for upsert
ALTER TABLE places DROP CONSTRAINT IF EXISTS places_name_unique;
ALTER TABLE places ADD CONSTRAINT places_name_unique UNIQUE (name);
